In [15]:
from PIL import Image
import numpy as np

w, h = 512, 512
data = np.zeros((h, w, 3), dtype=np.uint8)
data[150:362, 150:362] = [255, 0, 0]
      #len     width
img = Image.fromarray(data, 'RGB')
img.save('my.png')

img.show()

In [2]:
import cv2
import numpy as np
import matplotlib.image as image
img=image.imread('cat.jpg')
print('The Shape of the image is:',img.shape)
print('The image as array is:')
print(img)

img=cv2.imread('cat.jpg')
cv2.show()
cv2.waitKey(0)



The Shape of the image is: (600, 400, 3)
The image as array is:
[[[30 30 30]
  [30 30 30]
  [30 30 30]
  ...
  [31 30 28]
  [31 30 28]
  [31 30 28]]

 [[30 30 30]
  [30 30 30]
  [30 30 30]
  ...
  [32 31 29]
  [32 31 29]
  [32 31 29]]

 [[31 29 30]
  [31 29 30]
  [31 29 30]
  ...
  [33 32 30]
  [33 32 30]
  [33 32 30]]

 ...

 [[20 20 20]
  [20 20 20]
  [21 19 20]
  ...
  [48 39 32]
  [48 39 32]
  [48 39 32]]

 [[20 20 20]
  [20 20 20]
  [22 20 21]
  ...
  [44 37 31]
  [44 37 31]
  [44 37 31]]

 [[20 20 20]
  [20 20 20]
  [22 20 21]
  ...
  [42 35 29]
  [41 34 28]
  [41 34 28]]]


AttributeError: module 'cv2.cv2' has no attribute 'show'